### ISSUE TITLE
Design documents

### ISSUE THREAD

**Issue by andywynkoop** [uwgnol1612/WeCamp#1]
Hey Long! Here are a few suggestions for your proposal so far:
- [x] I don't think users will need a booking_id or review_id, you can get that info through the has_many association
- [x] spots should have an owner_id
- [x] spots and users will probably have images associated with them. While this info won't be in your schema, it should be included in your sample state

**Comment by uwgnol1612** [comment]
Hi Andy, thanks for the suggestions. I have made revisions accordingly.
